### ISSUE TITLE
Weird behaviour of 'q' key binding

### ISSUE THREAD

**Issue by patxoca** [statmobile/pydoc#5] opened 2015-04-02 17:41 UTC
It seems a bit weird that pydoc asks for a buffer when hitting the `q` key within the pydoc buffer.

May be you could consider using `bury-buffer` or `quit-window` instead of `kill-buffer`.

**Comment by jkitchin** [comment] 2015-04-02 19:54
I cannot reproduce this issue. pressing q just kills the buffer with no prompt.

**Comment by patxoca** [comment] 2015-04-02 20:34
That's what I have done in order to reproduce the issue in a clean environment:

``` bash

$ cd /tmp
$ git clone git@github.com:statmobile/pydoc.git
$ emacs -Q pydoc/pydoc.el
```

An then in emacs:

```
M-x eval-buffer
M-x pydoc RET httplib RET
q
```

Using emacs 24.4.1.

Here's (I expect) an screenshot:

![captura de 2015-04-02 22 19 38](https://cloud.githubusercontent.com/assets/2381168/6973053/4cad785e-d988-11e4-9c71-a729f3d78e9b.png)

**Comment by jkitchin** [comment] 2015-04-02 23:53
I can reproduce this this way, but not when I have the package loaded
through MELPA in my setup. Do you have pydoc installed via MELPA?

Alexis Roda writes:

> That's what I have done in order to reproduce the issue in a clean environment:
> 
> ``` bash
> 
> $ cd /tmp
> $ git clone git@github.com:statmobile/pydoc.git
> $ emacs -Q pydoc/pydoc.el
> ```
> 
> An then in emacs:
> 
> ```
> M-x eval-buffer
> M-x pydoc RET httplib RET
> q
> ```
> 
> Using emacs 24.4.1.
> 
> Here's (I expect) an screenshot:
> 
> ![captura de 2015-04-02 22 19 38](https://cloud.githubusercontent.com/assets/2381168/6973053/4cad785e-d988-11e4-9c71-a729f3d78e9b.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/statmobile/pydoc/issues/5#issuecomment-89038085

## 

Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by patxoca** [comment] 2015-04-03 09:50
I've done some digging and the problem seems related to the commit https://github.com/statmobile/pydoc/commit/813c8cc5986051edc98c09242def18a44aa1aef0

 `kill-buffer` behaves differently if called interactively or from code. `M-x kill-buffer` vs. `M-: (kill-buffer) RET`.

**Comment by jkitchin** [comment] 2015-04-03 15:18
Are you using the most recent version that defines it like (local-set-key "q" #'kill-buffer)? That version does not prompt me for a buffer name, it just kills the buffer.

**Comment by patxoca** [comment] 2015-04-03 18:12
I'm using https://github.com/patxoca/pydoc/blob/34dcb8c21dfc836f40fee83afe3cb577a0b8b06f/pydoc.el,  which is essentially the same as the current master (except from the faces). Tried with both, same result. This time I don't have an stale `pydoc.elc` hanging around, triple checked :-)

Out of curiosity, does `M-x kill-buffer RET` prompts you?

**Comment by jkitchin** [comment] 2015-04-03 18:19
yes, M-x kill-buffer RET prompts me.

John

---

Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by patxoca** [comment] 2015-04-04 07:08
My expectation is that binding `kill-buffer` _directly_ to `q` (in opposition to wrapping it within a `lambda`) should keep the _interactivity of the call_ and prompt for a buffer just as `M-x kill-buffer RET` does.

Could you try this code snippet, with both `emacs` and `emacs -Q`?

``` lisp
(defun test-command ()
  (interactive)
  (when (called-interactively-p)
    (message "Interactive")))

(defun wrapped-test-command ()
  (interactive)
  (test-command))

(local-set-key (kbd "<f6>") #'test-command)
(local-set-key (kbd "<f7>") #'wrapped-test-command)
```

In my setup both `F6` and `M-x test-command RET` display `Interactive` in the echo area, while `F7` and `M-: (test-command) RET` don't.

**Comment by jkitchin** [comment] 2015-05-26 01:46
I just pushed a fix to this finally, using quit-window. Hopefully that fixes it for you.

**Closed as completed by jkitchin** 2015-05-26 01:46 UTC
